import type { Topper, FeePackage, Facility, Course, Module, Lesson } from "@/types";

export const toppers: Topper[] = [
  {
    id: "1",
    name: "Ananya Sharma",
    rank: "AIR 42",
    exam: "UPSC CSE",
    year: 2024,
    quote: "Ibemhal IAS gave me the structured guidance and mentorship that turned my dream into reality. The answer writing practice was transformative.",
    avatar_url: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "2",
    name: "L. Tomba Singh",
    rank: "AIR 05",
    exam: "MPSC",
    year: 2024,
    quote: "The faculty's deep understanding of Manipur-specific subjects and current affairs gave me the edge I needed to crack the exam.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "3",
    name: "Priya Devi",
    rank: "AIR 18",
    exam: "UPSC CSE",
    year: 2023,
    quote: "The personalized mentorship at Ibemhal helped me identify my weaknesses and convert them into strengths. Best decision of my life.",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "4",
    name: "Rahul Meitei",
    rank: "AIR 67",
    exam: "UPSC CSE",
    year: 2024,
    quote: "From Foundation course to Interview guidance, Ibemhal was with me every step. The test series is unmatched in quality.",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "5",
    name: "Sneha Devi",
    rank: "AIR 12",
    exam: "MPSC",
    year: 2023,
    quote: "The integrated approach covering both Prelims and Mains simultaneously saved me years of preparation time.",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "6",
    name: "Vikram Singh",
    rank: "AIR 31",
    exam: "UPSC CSE",
    year: 2022,
    quote: "Ibemhal's focus on answer writing from day one made all the difference. I went from zero to writing 200+ words answers confidently.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
  },
];

export const feePackages: FeePackage[] = [
  {
    id: "1",
    name: "Foundation Batch",
    description: "Comprehensive 12-month program covering complete UPSC syllabus from scratch",
    price: 125000,
    emi_monthly: 11500,
    emi_months: 12,
    features: [
      "Complete GS Paper I-IV coverage",
      "Daily answer writing practice",
      "Weekly current affairs classes",
      "Monthly test series (Prelims + Mains)",
      "Personal mentorship sessions",
      "Study material & handouts",
      "Interview guidance program",
    ],
  },
  {
    id: "2",
    name: "Mains Special",
    description: "Intensive 6-month program focused on Mains answer writing & optional subject",
    price: 85000,
    emi_monthly: 8000,
    emi_months: 12,
    popular: true,
    features: [
      "GS Paper I-IV intensive coverage",
      "Daily answer writing with evaluation",
      "Optional subject coaching (any)",
      "8 full-length Mains tests",
      "Essay writing workshops",
      "Mentorship by retired officers",
      "Previous year paper analysis",
    ],
  },
  {
    id: "3",
    name: "Prelims Test Series",
    description: "Targeted test series with 30+ GS and CSAT practice tests",
    price: 25000,
    emi_monthly: 2500,
    emi_months: 12,
    features: [
      "20 Full-length GS tests",
      "10 CSAT practice tests",
      "Detailed solution & analysis",
      "All India ranking",
      "Performance analytics dashboard",
      "Doubt clearing sessions",
      "Current affairs compilation",
    ],
  },
  {
    id: "4",
    name: "Optional Subject",
    description: "Subject-wise coaching with expert faculty for your chosen optional",
    price: 45000,
    emi_monthly: 4500,
    emi_months: 12,
    features: [
      "Complete syllabus coverage (Paper I & II)",
      "Topic-wise tests & evaluation",
      "Previous 10 years paper analysis",
      "Answer writing framework",
      "Monthly current affairs for optional",
      "One-on-one doubt sessions",
      "Special handbooks & notes",
    ],
  },
];

export const facilities: Facility[] = [
  {
    id: "1",
    name: "Smart AC Classrooms",
    description: "State-of-the-art air-conditioned classrooms equipped with digital projectors and sound systems for an optimal learning environment.",
    image_url: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&h=400&fit=crop",
    location: "All Centers",
  },
  {
    id: "2",
    name: "1,000+ Book Library",
    description: "Comprehensive collection of UPSC/MPSC reference books, journals, newspapers, and previous year papers available 12 hours daily.",
    image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&h=400&fit=crop",
    location: "Keishampat Main Campus",
  },
  {
    id: "3",
    name: "Dedicated Study Spaces",
    description: "Silent study zones, group discussion rooms, and individual carrels for focused preparation throughout the day.",
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
    location: "All Centers",
  },
  {
    id: "4",
    name: "Keishampat Center",
    description: "Our flagship center in the heart of Imphal with all modern amenities and experienced faculty under one roof.",
    image_url: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop",
    location: "Keishampat, Imphal",
  },
  {
    id: "5",
    name: "Chingmeirong Center",
    description: "Well-connected center serving aspirants from eastern Imphal with dedicated batch timings and personalized attention.",
    image_url: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&h=400&fit=crop",
    location: "Chingmeirong, Imphal",
  },
  {
    id: "6",
    name: "Thangmeirand Center",
    description: "Newest center with modern infrastructure, spacious classrooms, and a growing community of serious aspirants.",
    image_url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=400&fit=crop",
    location: "Thangmeirand, Imphal",
  },
];

export const courses: Course[] = [
  {
    id: "1",
    title: "UPSC Foundation Course 2025",
    slug: "upsc-foundation-2025",
    description: "Comprehensive foundation program covering all aspects of UPSC CSE preparation from basics to advanced.",
    thumbnail_url: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=340&fit=crop",
    price: 125000,
    category: "foundation",
    level: "beginner",
    created_at: "2024-01-15",
  },
  {
    id: "2",
    title: "Mains Answer Writing Mastery",
    slug: "mains-answer-writing-mastery",
    description: "Intensive program to master the art of answer writing for UPSC Mains examination.",
    thumbnail_url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=340&fit=crop",
    price: 85000,
    category: "mains",
    level: "intermediate",
    created_at: "2024-02-01",
  },
  {
    id: "3",
    title: "Prelims Test Series Pro",
    slug: "prelims-test-series-pro",
    description: "30+ full-length tests with detailed analysis and All India ranking for serious aspirants.",
    thumbnail_url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=340&fit=crop",
    price: 25000,
    category: "test-series",
    level: "intermediate",
    created_at: "2024-03-01",
  },
  {
    id: "4",
    title: "Indian Polity - Complete",
    slug: "indian-polity-complete",
    description: "Deep dive into Indian Constitution, governance, and political system for both Prelims and Mains.",
    thumbnail_url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=340&fit=crop",
    price: 15000,
    category: "mains",
    level: "beginner",
    created_at: "2024-03-15",
  },
  {
    id: "5",
    title: "Geography Optional",
    slug: "geography-optional",
    description: "Complete Geography optional coaching by subject experts with comprehensive notes and tests.",
    thumbnail_url: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=600&h=340&fit=crop",
    price: 45000,
    category: "optional",
    level: "advanced",
    created_at: "2024-04-01",
  },
  {
    id: "6",
    title: "Current Affairs Yearly",
    slug: "current-affairs-yearly",
    description: "Daily current affairs analysis, monthly compilations, and special sessions on government schemes.",
    thumbnail_url: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=340&fit=crop",
    price: 12000,
    category: "prelims",
    level: "beginner",
    created_at: "2024-04-15",
  },
];

export const sampleModules: Module[] = [
  { id: "m1", course_id: "1", title: "Introduction to UPSC", order_index: 1, description: "Understanding the exam pattern and preparation strategy" },
  { id: "m2", course_id: "1", title: "Indian History", order_index: 2, description: "Ancient, Medieval, and Modern Indian History" },
  { id: "m3", course_id: "1", title: "Indian Polity", order_index: 3, description: "Constitution, Governance, and Political System" },
  { id: "m4", course_id: "1", title: "Indian Economy", order_index: 4, description: "Economic concepts, Budget, and Policy" },
  { id: "m5", course_id: "1", title: "Geography", order_index: 5, description: "Physical, Human, and Indian Geography" },
];

export const sampleLessons: Lesson[] = [
  { id: "l1", module_id: "m1", title: "UPSC Exam Pattern & Syllabus Overview", video_mux_id: "demo-1", duration_seconds: 1845, is_free_preview: true, order_index: 1 },
  { id: "l2", module_id: "m1", title: "How to Read NCERT Books Effectively", video_mux_id: "demo-2", duration_seconds: 2400, is_free_preview: true, order_index: 2 },
  { id: "l3", module_id: "m1", title: "Making Notes: The Ibemhal Method", video_mux_id: "demo-3", duration_seconds: 1920, is_free_preview: false, order_index: 3 },
  { id: "l4", module_id: "m2", title: "Ancient India: Indus Valley Civilization", video_mux_id: "demo-4", duration_seconds: 3100, is_free_preview: false, order_index: 1 },
  { id: "l5", module_id: "m2", title: "Vedic Period & Mahajanapadas", video_mux_id: "demo-5", duration_seconds: 2800, is_free_preview: false, order_index: 2 },
  { id: "l6", module_id: "m2", title: "Mauryan Empire & Ashoka", video_mux_id: "demo-6", duration_seconds: 3400, is_free_preview: false, order_index: 3 },
  { id: "l7", module_id: "m3", title: "Historical Background of Constitution", video_mux_id: "demo-7", duration_seconds: 2200, is_free_preview: false, order_index: 1 },
  { id: "l8", module_id: "m3", title: "Preamble & Salient Features", video_mux_id: "demo-8", duration_seconds: 1900, is_free_preview: false, order_index: 2 },
];
